CREATE TABLE `USER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`USERNAME` VARCHAR(50) DEFAULT NULL COMMENT '用户名',
	`PASSWORD` VARCHAR(50) DEFAULT NULL COMMENT '登录密码',
	`SEX` INT(5) DEFAULT NULL COMMENT '性别',
	`CREATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`MOBILE` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='用户表';

CREATE TABLE `ADDRESS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`USERID` INT(50) DEFAULT NULL COMMENT '用户ID',
	`CONSIGNEE` VARCHAR(50) DEFAULT NULL COMMENT '收货人',
	`MOBILE` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
	`AREA` VARCHAR(20) DEFAULT NULL COMMENT '所在地区',
	`ADDRESS` VARCHAR(50) DEFAULT NULL COMMENT '详细地址',
	`ISDEFAULT` TINYINT(1) DEFAULT '1' COMMENT '是否默认地址',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='收货地址表';


CREATE TABLE `GOODS` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`NAME` VARCHAR(100) DEFAULT NULL COMMENT '商品名称',
	`PRICE` DECIMAL(4,2) DEFAULT NULL COMMENT '单价',
	`DESCRIPTION` TEXT DEFAULT NULL COMMENT '商品介绍',
	`SHOPID` INT(11) DEFAULT NULL COMMENT '店铺ID',
	`FREIGHT` DECIMAL(4,2) DEFAULT NULL COMMENT '运费',
	`ISDEFAULT` TINYINT(1) DEFAULT '1' COMMENT '是否默认地址',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='商品表';

CREATE TABLE `SHOP` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`SHOPNAME` VARCHAR(100) DEFAULT NULL COMMENT '店铺名称',
	`CREATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '开店时间',
	`DESCRIPTION` TEXT DEFAULT NULL COMMENT '店铺介绍',
	`AREA` VARCHAR(20) DEFAULT NULL COMMENT '所在地区',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='店铺表';

CREATE TABLE `ORDER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`ORDERNO` VARCHAR(200) DEFAULT NULL COMMENT '订单编号',
	`CREATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`PAYTIME` DATETIME DEFAULT NULL COMMENT '付款时间',
	`SENDTIME` DATETIME DEFAULT NULL COMMENT '发货时间',
	`DISTRIBUTION` INT(11) DEFAULT NULL COMMENT '配送ID',
	`REALPAY` DECIMAL(4,2) DEFAULT NULL COMMENT '实付金额',
	`DISCOUNTAMOUNT` DECIMAL(4,2) DEFAULT NULL COMMENT '优惠金额',
	`TOTALPRICE` DECIMAL(4,2) DEFAULT NULL COMMENT '商品总价',
	`ADDRESSID` INT(11) DEFAULT NULL COMMENT '收货地址ID',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='订单表';

CREATE TABLE `ORDERDETAIL` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`ORDERID` INT(11) DEFAULT NULL COMMENT '订单ID',
	`GOODSID` INT(11) DEFAULT NULL COMMENT '商品ID',
	`COUNT` INT(10) DEFAULT NULL COMMENT '商品数量',
	`REALPAY` DECIMAL(4,2) DEFAULT NULL COMMENT '实付金额',
	`DISCOUNTAMOUNT` DECIMAL(4,2) DEFAULT NULL COMMENT '优惠金额',
	`TOTALPRICE` DECIMAL(4,2) DEFAULT NULL COMMENT '商品总价',
	`ISRETURN` TINYINT(1) DEFAULT '0' COMMENT '是否退货',
	`SALESRETURNID` INT(11) DEFAULT NULL COMMENT '退货ID',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='订单详情表';

CREATE TABLE `SALESRETURN` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`ORDERID` VARCHAR(200) DEFAULT NULL COMMENT '退货编号',
	`CREATETIME` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	`RETURNTIME` DATETIME DEFAULT NULL COMMENT '退货时间',
	`REASON` VARCHAR(200) DEFAULT NULL COMMENT '退货原因',
	`RETURNPRICE` DECIMAL(4,2) DEFAULT NULL COMMENT '退货金额',
	`REALPAY` INT(10) DEFAULT NULL COMMENT '退货数量',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='退货表';


CREATE TABLE `DISTRIBUTION` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`DISTRIBUTIONNAME` VARCHAR(200) DEFAULT NULL COMMENT '退货编号',
	`DISTRIBUTIONSTATUS` VARCHAR(200) DEFAULT NULL COMMENT '配送状态',
	`MEMO` VARCHAR(500) DEFAULT NULL COMMENT '备注',
	PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 COMMENT='配送表';





